#!/bin/bash

root=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; cd .. ; pwd -P )

protoc \
  --go_out=. \
  --go-grpc_out=. \
  --go_opt=paths=source_relative \
  --go-grpc_opt=paths=source_relative \
  proto/hello.proto

protoc -I=$root/proto hello.proto \
  --js_out=import_style=commonjs:$root/web/src/proto

protoc -I=$root/proto hello.proto \
  --grpc-web_out=import_style=commonjs,mode=grpcwebtext:$root/web/src/proto

if [[ "$1" ]]; then
  echo "$ go build ./$1"
  go build -o ./target/$1 ./$1

  echo
else
  binaries="client server"

  for binary in $binaries
  do
    echo "$ go build ./$binary"
    go build -o ./target/$binary ./$binary

    echo
  done
fi
