#!/bin/bash

protoc \
  --go_out=. \
  --go-grpc_out=. \
  --go_opt=paths=source_relative \
  --go-grpc_opt=paths=source_relative \
  proto/hello.proto

if [[ "$1" ]]; then
  echo "$ go build ./$1"
  go build -o ./target/$1 ./$1

  echo
else
  binaries="client server"

  for binary in $binaries
  do
    echo "$ go build ./$binary"
    go build -o ./target/$binary ./$binary

    echo
  done
fi
